import { drizzle } from "drizzle-orm/mysql2";
import mysql from "mysql2/promise";
import "dotenv/config";

const connection = await mysql.createConnection(process.env.DATABASE_URL);
const db = drizzle(connection);

// ── Suppliers ─────────────────────────────────────────────────────────────────
const suppliers = [
  // Builders Merchants
  {
    name: "Island Builders Merchant",
    description: "One of Ireland's largest builders merchants with a strong presence across the island. Stocks timber, bricks, blocks, cement, insulation, and general building materials.",
    category: "builders_merchants",
    region: "Belfast",
    isNational: true,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.03,
    isActive: true,
  },
  {
    name: "Capital Building Supplies",
    description: "Leading independent builders merchant with branches across the island of Ireland. Excellent range of timber, sheet materials, and building supplies.",
    category: "builders_merchants",
    region: "the island of Ireland",
    isNational: false,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.04,
    isActive: true,
  },
  {
    name: "Premier Build Centre",
    description: "National builders merchant with competitive pricing on blocks, bricks, cement, sand, and aggregates. Branches across Ireland.",
    category: "builders_merchants",
    region: "Dublin",
    isNational: true,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.03,
    isActive: true,
  },
  // Timber Merchants
  {
    name: "Greenfield Timber & Sheet",
    description: "Specialist timber and sheet materials merchant. Trusted by tradespeople across the island of Ireland for quality hardwood and softwood.",
    category: "timber_merchants",
    region: "Belfast",
    isNational: false,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.04,
    isActive: true,
  },
  {
    name: "Atlantic Timber Supplies",
    description: "Long-established timber merchant supplying tradespeople and homeowners with quality softwood, hardwood, and sheet materials.",
    category: "timber_merchants",
    region: "Galway",
    isNational: false,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.04,
    isActive: true,
  },
  // Paint & Decorating
  {
    name: "Prestige Decorating Centre",
    description: "Professional decorating supplies and premium paint ranges. Trade accounts available with discounts for regular customers.",
    category: "paint_decorating",
    region: "Belfast",
    isNational: true,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.05,
    isActive: true,
  },
  {
    name: "Colour & Craft Supplies",
    description: "Specialist paint and decorating supplies. Full trade range of paints, wallpaper, tools, and sundries for professional decorators and DIY enthusiasts.",
    category: "paint_decorating",
    region: "Dublin",
    isNational: true,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.05,
    isActive: true,
  },
  // Flooring
  {
    name: "Cornerstone Tile & Stone",
    description: "Ireland's premier tile showroom. Huge range of floor and wall tiles, natural stone, and LVT flooring with expert design advice.",
    category: "flooring",
    region: "Belfast",
    isNational: false,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.05,
    isActive: true,
  },
  {
    name: "Luxe Flooring Ireland",
    description: "Premium luxury vinyl tile and plank flooring. Realistic wood and stone effects with excellent durability for residential and commercial projects.",
    category: "flooring",
    region: "the island of Ireland",
    isNational: true,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.06,
    isActive: true,
  },
  // Kitchen & Bathroom
  {
    name: "Aqua Bathroom Studio",
    description: "Complete bathroom solutions from suites to tiles and accessories. Design service available for full bathroom renovations.",
    category: "kitchen_bathroom",
    region: "Belfast",
    isNational: true,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.05,
    isActive: true,
  },
  {
    name: "Hearth Kitchen Showroom",
    description: "Quality kitchen units and worktops at competitive prices. Wide range of door styles and finishes with full installation service available.",
    category: "kitchen_bathroom",
    region: "Dublin",
    isNational: false,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.05,
    isActive: true,
  },
  // Electrical & Plumbing
  {
    name: "Volt Electrical Wholesale",
    description: "Leading electrical wholesale distributor. Full range of cables, consumer units, lighting, and accessories at trade prices.",
    category: "electrical_plumbing",
    region: "Belfast",
    isNational: true,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.04,
    isActive: true,
  },
  {
    name: "Flow Plumbing & Heating",
    description: "Specialist plumbing and heating merchant. Full range of pipes, fittings, boilers, radiators, and bathroom products at trade prices.",
    category: "electrical_plumbing",
    region: "Cork",
    isNational: false,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.04,
    isActive: true,
  },
  // Windows & Doors
  {
    name: "Clearview Windows & Doors",
    description: "Ireland's leading window and door manufacturer. uPVC, aluminium, and composite doors with full installation service.",
    category: "windows_doors",
    region: "the island of Ireland",
    isNational: false,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.05,
    isActive: true,
  },
  // Roofing & Insulation
  {
    name: "Summit Roofing Supplies",
    description: "Specialist roofing materials supplier. Full range of tiles, slates, felt, insulation, and roofline products for contractors and self-builders.",
    category: "roofing_insulation",
    region: "Belfast",
    isNational: true,
    websiteUrl: null,
    phone: null,
    address: null,
    commissionRate: 0.04,
    isActive: true,
  },
];

// ── Tradespeople ──────────────────────────────────────────────────────────────
const tradespeople = [
  {
    name: "Oakwood Joinery",
    trade: "joiner_carpenter",
    bio: "25 years experience in bespoke joinery, fitted kitchens, and staircases across Belfast and Greater Belfast. Fully insured with all work guaranteed.",
    region: "Belfast",
    phone: null,
    isVerified: true,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: "Clearflow Plumbing",
    trade: "plumber",
    bio: "Gas Safe registered plumber covering Belfast and Antrim. Specialising in bathroom installations, boiler replacements, and emergency call-outs.",
    region: "Belfast",
    phone: null,
    isVerified: true,
    averageRating: 4.9,
    isActive: true,
  },
  {
    name: "Brightline Electrical",
    trade: "electrician",
    bio: "NICEIC-approved electrician with 18 years experience. Full rewires, consumer unit upgrades, EV charger installations, and electrical testing across Ireland.",
    region: "Antrim",
    phone: null,
    isVerified: true,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: "Smooth Finish Plastering",
    trade: "plasterer",
    bio: "Specialist plasterer covering all of Ireland. Skimming, dot and dab, dry lining, and Venetian plaster finishes. Over 15 years in the trade.",
    region: "Armagh",
    phone: null,
    isVerified: true,
    averageRating: 4.6,
    isActive: true,
  },
  {
    name: "Prestige Painting & Decorating",
    trade: "painter_decorator",
    bio: "Professional painter and decorator based in Lisburn. Interior and exterior work, wallpapering, and specialist finishes. Fully insured.",
    region: "Lisburn",
    phone: null,
    isVerified: true,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: "Ridgeline Roofing",
    trade: "roofer",
    bio: "Experienced roofer covering Belfast and Down. Slate, tile, flat roofing, and guttering. Emergency repairs and full re-roofs. NFRC member.",
    region: "Down",
    phone: null,
    isVerified: true,
    averageRating: 4.5,
    isActive: true,
  },
  {
    name: "Precision Tiling",
    trade: "tiler",
    bio: "Expert wall and floor tiler with 20 years experience. Bathrooms, kitchens, hallways, and commercial projects. All tile types including large format.",
    region: "Belfast",
    phone: null,
    isVerified: true,
    averageRating: 4.9,
    isActive: true,
  },
  {
    name: "Cornerstone Building",
    trade: "builder_general",
    bio: "General builder and project manager covering all of Ireland. Extensions, conversions, structural work, and full renovations. 30 years experience.",
    region: "Derry",
    phone: null,
    isVerified: true,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: "Fitted Kitchen Specialists",
    trade: "kitchen_fitter",
    bio: "Specialist kitchen fitter based in Belfast. Full kitchen installations including tiling, plumbing connections, and electrical first fix. 12 years experience.",
    region: "Belfast",
    phone: null,
    isVerified: true,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: "Aqua Bathroom Fitting",
    trade: "bathroom_fitter",
    bio: "Complete bathroom renovation specialist. Design, supply, and installation of full bathroom suites. Tiling, plumbing, and electrics all in-house.",
    region: "Belfast",
    phone: null,
    isVerified: true,
    averageRating: 4.9,
    isActive: true,
  },
  {
    name: "Greenscape Landscaping",
    trade: "landscaper",
    bio: "Full landscaping service covering Belfast and surrounding areas. Patios, decking, fencing, driveways, and garden design. Free quotes available.",
    region: "Belfast",
    phone: null,
    isVerified: false,
    averageRating: 4.4,
    isActive: true,
  },
  {
    name: "Craftwood Carpentry",
    trade: "joiner_carpenter",
    bio: "Skilled carpenter specialising in fitted wardrobes, home offices, and bespoke furniture. Based in Derry, covering the north-west.",
    region: "Derry",
    phone: null,
    isVerified: true,
    averageRating: 4.6,
    isActive: true,
  },
  {
    name: "Heatwise Plumbing & Heating",
    trade: "plumber",
    bio: "Gas Safe registered heating engineer covering Antrim and Down. Boiler installations, underfloor heating, and full central heating systems.",
    region: "Antrim",
    phone: null,
    isVerified: true,
    averageRating: 4.7,
    isActive: true,
  },
  {
    name: "Smartwire Electrical",
    trade: "electrician",
    bio: "Domestic and commercial electrician based in Newry. Smart home installations, solar PV, and EV charging specialists. NICEIC approved.",
    region: "Newry",
    phone: null,
    isVerified: true,
    averageRating: 4.8,
    isActive: true,
  },
  {
    name: "Colourcraft Decorating",
    trade: "painter_decorator",
    bio: "Experienced painter and decorator covering Armagh and surrounding areas. Residential and commercial. Competitive rates and quality finish guaranteed.",
    region: "Armagh",
    phone: null,
    isVerified: false,
    averageRating: 4.3,
    isActive: true,
  },
];

// ── Insert ────────────────────────────────────────────────────────────────────
console.log("Seeding suppliers...");
for (const supplier of suppliers) {
  await connection.execute(
    `INSERT IGNORE INTO suppliers (name, description, category, region, isNational, websiteUrl, phone, address, commissionRate, isActive)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      supplier.name,
      supplier.description,
      supplier.category,
      supplier.region,
      supplier.isNational ? 1 : 0,
      supplier.websiteUrl ?? null,
      supplier.phone ?? null,
      supplier.address ?? null,
      supplier.commissionRate ?? 0.03,
      supplier.isActive ? 1 : 0,
    ]
  );
  console.log(`  ✓ ${supplier.name}`);
}

console.log("\nSeeding tradespeople...");
for (const tp of tradespeople) {
  await connection.execute(
    `INSERT IGNORE INTO tradespeople (name, trade, bio, region, phone, isVerified, averageRating, isActive)
     VALUES (?, ?, ?, ?, ?, ?, ?, ?)`,
    [
      tp.name,
      tp.trade,
      tp.bio,
      tp.region,
      tp.phone ?? null,
      tp.isVerified ? 1 : 0,
      tp.averageRating ?? 4.5,
      tp.isActive ? 1 : 0,
    ]
  );
  console.log(`  ✓ ${tp.name}`);
}

console.log("\n✅ Seed complete.");
await connection.end();
